server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/testcopy
        username: ****
        password: ****
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver

    thymeleaf:
      cache: false # 开发时关闭缓存,不然没法看到实时页面
      mode: LEGACYHTML5 # 用非严格的 HTML
      encoding: UTF-8
      servlet:
        content-type: text/html

mybatis:
  type-aliases-package: com.example.demo.pojo
  mapper-locations: classpath:mappers/*.xml